---
deployment:
  tasks:
    - export DEPLOYPATH=/home/desarrolloupward/public_html
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH